apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}-frontend-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}-frontend-deployment-canary
  minReplicas: {{ .Values.frontend.canary.hpa.minReplicas }}
  maxReplicas: {{ .Values.frontend.canary.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.frontend.canary.hpa.resource.cpu.UtilizationPercentage }}