apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Chart.Name }}-gateway
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}-gateway
  annotations:
    gateway.kgateway.io/proxy-readiness-port: "19000"
    gateway.kgateway.io/proxy-startup-port: "19000"

spec:
  gatewayClassName: kgateway
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: Same