apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Chart.Name }}-account-deployment-stable
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}-account
    version: {{ .Values.account.stable.version }}
spec:
  replicas: {{ .Values.account.stable.replicas }} 
  selector: 
    matchLabels:
      app: {{ .Chart.Name }}-account
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-account
        version: {{ .Values.account.stable.version }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-account-container
          image: {{ .Values.account.stable.image.repository }}:{{ .Values.account.stable.image.tag }}
          resources:
            requests:
              memory: {{ .Values.account.stable.resources.requests.memory }}
              cpu: {{ .Values.account.stable.resources.requests.cpu }}
            limits:
              memory: {{ .Values.account.stable.resources.limits.memory }}
              cpu: {{ .Values.account.stable.resources.limits.cpu }}
          ports:
            - containerPort: {{ .Values.account.port }}
          envFrom:
            - secretRef:
                name: {{ .Chart.Name }}-account-secret
            - configMapRef:
                name: {{ .Chart.Name }}-account-config
          startupProbe:
            httpGet:
              path: /health
              port: {{ .Values.account.port }}
            initialDelaySeconds: 5
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.account.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.account.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3