apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-payment-deployment-canary
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}-payment
    version: {{ .Values.payment.canary.version }}

spec:
  replicas: {{ .Values.payment.canary.replicas }}

  selector:
    matchLabels:
      app: {{ .Chart.Name }}-payment

  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-payment
        version: {{ .Values.payment.canary.version }}

    spec:
      containers:
        - name: {{ .Chart.Name }}-payment-container

          image: {{ .Values.payment.canary.image.repository }}:{{ .Values.payment.canary.image.tag }}

          resources:
            requests:
              memory: {{ .Values.payment.canary.resources.requests.memory }}
              cpu: {{ .Values.payment.canary.resources.requests.cpu }}
            limits:
              memory: {{ .Values.payment.canary.resources.limits.memory }}
              cpu: {{ .Values.payment.canary.resources.limits.cpu }}

          ports:
            - containerPort: {{ .Values.payment.port }}

          envFrom:
            - secretRef:
                name: {{ .Chart.Name }}-payment-secret
            - configMapRef:
                name: {{ .Chart.Name }}-payment-config

          startupProbe:
            httpGet:
              path: /health
              port: {{ .Values.payment.port }}
            initialDelaySeconds: 5
            failureThreshold: 30
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.payment.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.payment.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3