apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-payment-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}-payment
  ports:
    - port: {{ .Values.payment.port }}
      targetPort: {{ .Values.payment.port }}
  type: {{ .Values.payment.service.type }}