namespace: banking-app

account:
  image: 
    repository: "yaswanthreddy1602/account-service"
    tag: "v1"
  replicas: 2
  port: "3002"
  resources:
    requests:
      cpu: "50m"
      memory: "32Mi"
    limits:
      cpu: "100m"
      memory: "256Mi"
  env:
    dbHost: "mysql"
    dbUser: "root"
    dbPass: "rootpassword"
    dbName: "banking_db"
    redisHost: "redis"
  service:
    type: NodePort

config:
  image:
    repository: "yaswanthreddy1602/config-service"
    tag: "v1"
  replicas: 2
  port: "3008"
  resources:
    requests:
      cpu: "50m"
      memory: "32Mi"
    limits:
      cpu: "100m"
      memory: "256Mi"
  service:
    type: NodePort

fraud:
  image:
    repository: "yaswanthreddy1602/fraud-detection-service"
    tag: "v1"
  replicas: 2
  port: "3007"
  resources:
    requests:
      cpu: "50m"
      memory: "32Mi"
    limits:
      cpu: "100m"
      memory: "256Mi"
  service:
    type: NodePort
  env:
    mqUrl: "amqp://rabbitmq"

frontend:
  image:
    repository: "thamizhanm3/bank-frontend"
    tag: "v1"
  replicas: 2
  port: "80"
  resources:
    requests:
      cpu: "50m"
      memory: "32Mi"
    limits:
      cpu: "100m"
      memory: "256Mi"
  service:
    type: NodePort
  env:
    userUrl: "/api/user"
    accountUrl: "/api/account"
    txUrl: "/api/tx"
    loanUrl: "/api/loan"
    reportUrl: "/api/report"

loan:
  image:
    repository: "yaswanthreddy1602/loan-service"
    tag: "v1"
  replicas: 2
  port: "3005"
  resources:
    requests:
      cpu: "50m"
      memory: "32Mi"
    limits:
      cpu: "100m"
      memory: "256Mi"
  service:
    type: NodePort
  env:
    dbHost: "mysql"
    dbUser: "root"
    dbPass: "rootpassword"
    dbName: "banking_db"
    redisHost: "redis"

notification:
  image:
    repository: "yaswanthreddy1602/notification-service"
    tag: "v1"
  replicas: 2
  port: "3006"
  resources:
    requests:
      cpu: "50m"
      memory: "32Mi"
    limits:
      cpu: "100m"
      memory: "256Mi"
  service:
    type: NodePort
  env:
    mqUrl: "amqp://rabbitmq"
  
payment:
  image:
    repository: "yaswanthreddy1602/payment-service"
    tag: "v1"
  replicas: 2
  port: "3004"
  resources:
    requests:
      cpu: "50m"
      memory: "32Mi"
    limits:
      cpu: "100m"
      memory: "256Mi"
  env:
    accountUrl: "http://account-service:3002"