namespace: banking-app

account:
  stable:
    version: "stable"
    image:
      repository: "yaswanthreddy1602/account-service"
      tag: "v1"
    replicas: 2
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"
    hpa:
      enabled: true
      minReplicas: 2
      maxReplicas: 6
      resource:
        cpu:
          UtilizationPercentage: 70
  canary:
    version: "canary"
    image:
      repository: "yaswanthreddy1602/account-service"
      tag: "v1"
    replicas: 1
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      resource:
        cpu:
          UtilizationPercentage: 70
  port: "3002"
  resources:
    requests:
      cpu: "10m"
      memory: "32Mi"
    limits:
      cpu: "100m"
      memory: "256Mi"
  env:
    dbHost: "mysql"
    dbUser: "root"
    dbPass: "rootpassword"
    dbName: "banking_db"
    redisHost: "redis"
  service:
    type: NodePort

config:
  image:
    repository: "yaswanthreddy1602/config-service"
    tag: "v1"
  replicas: 2
  port: "3008"
  resources:
    requests:
      cpu: "10m"
      memory: "32Mi"
    limits:
      cpu: "100m"
      memory: "256Mi"
  service:
    type: NodePort
  stable:
    version: "stable"
    image:
      repository: "yaswanthreddy1602/config-service"
      tag: "v1"
    replicas: 2
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"
  canary:
    version: "canary"
    image:
      repository: "yaswanthreddy1602/config-service"
      tag: "v1"
    replicas: 1
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"

fraud:
  stable:
    version: "stable"
    image:
      repository: "yaswanthreddy1602/fraud-detection-service"
      tag: "v1"
    replicas: 2
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"
    vpa:
      enabled: true
      updateMode: "Off"
  canary:
    version: "canary"
    image:
      repository: "yaswanthreddy1602/fraud-detection-service"
      tag: "v1"
    replicas: 1
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"
    vpa:
      enabled: true
      updateMode: "Off"
  port: "3007"
  resources:
    requests:
      cpu: "10m"
      memory: "32Mi"
    limits:
      cpu: "100m"
      memory: "256Mi"
  service:
    type: NodePort
  env:
    mqUrl: "amqp://rabbitmq"

frontend:
  stable:
    version: "stable"
    image:
      repository: "thamizhanm3/bank-frontend"
      tag: "v1"
    replicas: 2
    hpa:
      enabled: true
      minReplicas: 2
      maxReplicas: 6
      resource:
        cpu:
          UtilizationPercentage: 70
  canary:
    version: "canary"
    image:
      repository: "thamizhanm3/bank-frontend"
      tag: "v1"
    replicas: 1
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      resource:
        cpu:
          UtilizationPercentage: 70
  port: "80"
  resources:
    requests:
      cpu: "10m"
      memory: "32Mi"
    limits:
      cpu: "100m"
      memory: "256Mi"
  service:
    type: NodePort
  env:
    userUrl: "/api/user"
    accountUrl: "/api/account"
    txUrl: "/api/tx"
    loanUrl: "/api/loan"
    reportUrl: "/api/report"

loan:
  stable:
    version: "stable"
    image:
      repository: "yaswanthreddy1602/loan-service"
      tag: "v1"
    replicas: 2
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"
    hpa:
      enabled: true
      minReplicas: 2
      maxReplicas: 6
      resource:
        cpu:
          UtilizationPercentage: 70

  canary:
    version: "canary"
    image:
      repository: "yaswanthreddy1602/loan-service"
      tag: "v1"
    replicas: 1
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      resource:
        cpu:
          UtilizationPercentage: 70

  port: "3005"

  env:
    dbHost: "mysql"
    dbUser: "root"
    dbPass: "rootpassword"
    dbName: "banking_db"
    redisHost: "redis"

  service:
    type: NodePort

notification:
  image:
    repository: "yaswanthreddy1602/notification-service"
    tag: "v1"
  replicas: 2
  port: "3006"
  resources:
    requests:
      cpu: "10m"
      memory: "32Mi"
    limits:
      cpu: "100m"
      memory: "256Mi"
  service:
    type: NodePort
  env:
    mqUrl: "amqp://rabbitmq"
  
payment:
  stable:
    version: "stable"
    image:
      repository: "yaswanthreddy1602/payment-service"
      tag: "v1"
    replicas: 2
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"
    hpa:
      enabled: true
      minReplicas: 2
      maxReplicas: 6
      resource:
        cpu:
          UtilizationPercentage: 70

  canary:
    version: "canary"
    image:
      repository: "yaswanthreddy1602/payment-service"
      tag: "v1"
    replicas: 1
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      resource:
        cpu:
          UtilizationPercentage: 70

  port: "3004"

  env:
    accountUrl: "http://account-service:3002"

  service:
    type: NodePort

reporting:
  stable:
    version: "stable"
    image:
      repository: "yaswanthreddy1602/reporting-service"
      tag: "v1"
    replicas: 2
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"
    vpa:
      enabled: true
      updateMode: "Off"
  canary:
    version: "canary"
    image:
      repository: "yaswanthreddy1602/reporting-service"
      tag: "v1"
    replicas: 1
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"
    vpa:
      enabled: true
      updateMode: "Off"
  port: "3010"
  resources:
    requests:
      cpu: "10m"
      memory: "32Mi"
    limits:
      cpu: "100m"
      memory: "256Mi"
  env:
    dbHost: "mysql"
    dbUser: "root"
    dbPass: "rootpassword"
    dbName: "banking_db"
  service:
    type: NodePort

service:
  stable:
    version: "stable"
    image:
      repository: "yaswanthreddy1602/service-discovery"
      tag: "v1"
    replicas: 2
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"
  canary:
    version: "canary"
    image:
      repository: "yaswanthreddy1602/service-discovery"
      tag: "v1"
    replicas: 1
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"
  port: "3009"
  resources:
    requests:
      cpu: "10m"
      memory: "32Mi"
    limits:
      cpu: "100m"
      memory: "256Mi"
  service:
    type: NodePort

transaction:
  stable:
    version: "stable"
    image:
      repository: "yaswanthreddy1602/transaction-service"
      tag: "v1"
    replicas: 2
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"
    hpa:
      enabled: true
      minReplicas: 2
      maxReplicas: 6
      resource:
        cpu:
          UtilizationPercentage: 70

  canary:
    version: "canary"
    image:
      repository: "yaswanthreddy1602/transaction-service"
      tag: "v1"
    replicas: 1
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      resource:
        cpu:
          UtilizationPercentage: 70

  port: "3003"

  env:
    dbHost: "mysql"
    dbUser: "root"
    dbPass: "rootpassword"
    dbName: "banking_db"
    redisHost: "redis"
    mqUrl: "amqp://rabbitmq"

  service:
    type: NodePort

user:
  stable:
    version: "stable"
    image:
      repository: "yaswanthreddy1602/user-service"
      tag: "v1"
    replicas: 2
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"
    hpa:
      enabled: true
      minReplicas: 2
      maxReplicas: 6
      resource:
        cpu:
          UtilizationPercentage: 70
  canary:
    version: "canary"
    image:
      repository: "yaswanthreddy1602/user-service"
      tag: "v1"
    replicas: 1
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      resource:
        cpu:
          UtilizationPercentage: 70
  port: "3001"
  resources:
    requests:
      cpu: "10m"
      memory: "32Mi"
    limits:
      cpu: "100m"
      memory: "256Mi"
  env:
    dbHost: "mysql"
    dbUser: "root"
    dbPass: "rootpassword"
    dbName: "banking_db"
    redisHost: "redis"
  service:
    type: NodePort