apiVersion: v1
kind: Service
metadata: 
  name: {{ .Chart.Name }}-fraud-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}-fraud
  ports:
    - port: {{ .Values.fraud.port }}
      targetPort: {{ .Values.fraud.port }}
  type: {{ .Values.fraud.service.type }}