apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}-fraud-vpa-stable
  namespace: {{ .Values.namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}-fraud-deployment-stable
  updatePolicy:
    updateMode: "{{ .Values.fraud.stable.vpa.updateMode }}"