apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-notification-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}-notification
  ports:
  - port: {{ .Values.notification.port }}
    targetPort: {{ .Values.notification.port }}
  type: {{ .Values.notification.service.type }}