apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-mysql-config
  namespace: {{ .Values.namespace }}
data:
  primary.cnf: |
    {{ .Values.mysql.primaryCnf | indent 4 }}

  replica.cnf: |
    {{ .Values.mysql.replicaCnf | indent 4 }}