apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-mysql-config
  namespace: {{ .Values.namespace }}
data:
  primary.cnf: |
    [mysqld]
    log-bin=mysql-bin
    binlog_format=ROW
    gtid_mode=ON
    enforce_gtid_consistency=ON
    sync_binlog=1
    innodb_flush_log_at_trx_commit=1
    skip-host-cache
    skip-name-resolve

  replica.cnf: |
    [mysqld]
    super-read-only=1
    log-bin=mysql-bin
    binlog_format=ROW
    gtid_mode=ON
    enforce_gtid_consistency=ON
    log_replica_updates=ON
    relay-log=relay-bin
    skip-host-cache
    skip-name-resolve