apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-mysql-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.env.mySqlRootPassword }}
  MYSQL_REPLICATION_PASSWORD: {{ .Values.mysql.env.mySqlReplicationPassword }}