apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-mysql-read-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}-mysql
  ports:
  - port: {{ .Values.mysql.port }}