apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-redis-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-redis
    spec:
      containers:
      - name: {{ .Chart.Name }}-redis-container
        image: {{ .Values.redis.image }}
        command: ["redis-server", "--appendonly", "yes"]
        ports:
        - containerPort: {{ .Values.redis.port }}

        resources:
          requests:
            memory: {{ .Values.redis.resources.requests.memory }}
            cpu: {{ .Values.redis.resources.requests.cpu }}
          limits:
            memory: {{ .Values.redis.resources.limits.memory }}
            cpu: {{ .Values.redis.resources.limits.cpu }}
        startupProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          failureThreshold: 30
          periodSeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 5

        volumeMounts:
        - name: redis-data
          mountPath: /data

      volumes:
      - name: redis-data
        emptyDir: {}