apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-redis-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.redis.service.type }}
  selector:
    app: {{ .Chart.Name }}-redis
  ports:
  - port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}