apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-transaction-config
  namespace: {{ .Values.namespace }}
data:
  PORT: "{{ .Values.transaction.port }}"
  ACCOUNT_SVC_URL: "http://{{ .Chart.Name }}-account-service:{{ .Values.account.port }}"