apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Chart.Name }}-transaction-deployment-canary
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}-transaction
    version: {{ .Values.transaction.canary.version }}

spec:
  replicas: {{ .Values.transaction.canary.replicas }}

  selector:
    matchLabels:
      app: {{ .Chart.Name }}-transaction

  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-transaction
        version: {{ .Values.transaction.canary.version }}

    spec:
      containers:
        - name: {{ .Chart.Name }}-transaction

          image: {{ .Values.transaction.canary.image.repository }}:{{ .Values.transaction.canary.image.tag }}

          resources:
            requests:
              memory: {{ .Values.transaction.canary.resources.requests.memory }}
              cpu: {{ .Values.transaction.canary.resources.requests.cpu }}
            limits:
              memory: {{ .Values.transaction.canary.resources.limits.memory }}
              cpu: {{ .Values.transaction.canary.resources.limits.cpu }}

          ports:
            - containerPort: {{ .Values.transaction.port }}

          envFrom:
            - secretRef:
                name: {{ .Chart.Name }}-transaction-secret
            - configMapRef:
                name: {{ .Chart.Name }}-transaction-config

          startupProbe:
            httpGet:
              path: /health
              port: {{ .Values.transaction.port }}
            initialDelaySeconds: 5
            failureThreshold: 30
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.transaction.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.transaction.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3