apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Chart.Name }}-transaction-route
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
  - name: {{ .Chart.Name }}-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.transaction.gateway.path }}
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: {{ .Chart.Name }}-transaction-service
      port: {{ .Values.transaction.service.port }}