apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-transaction-secret
  namespace: {{ .Values.namespace }}
stringData:
  DB_HOST: "{{ .Values.transaction.env.dbHost }}"
  DB_USER: {{ .Values.transaction.env.dbUser }}
  DB_PASS: {{ .Values.transaction.env.dbPass }}
  DB_NAME: {{ .Values.transaction.env.dbName }}
  REDIS_HOST: {{ .Values.transaction.env.redisHost }}
  MQ_URL: {{ .Values.transaction.env.mqUrl }}