apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-config-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.config.service.type }}
  selector:
    app: {{ .Chart.Name }}-config
  ports:
    - port: {{ .Values.config.port }}
      targetPort: {{ .Values.config.port }}