apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-user-deployment-stable
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-user
    version: {{ .Values.user.stable.version }}
spec:
  replicas: {{ .Values.user.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-user
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-user
        version: {{ .Values.user.stable.version }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-user-container
          image: {{ .Values.user.stable.image.repository }}:{{ .Values.user.stable.image.tag }}
          resources:
            requests:
              memory: {{ .Values.user.stable.resources.requests.memory }}
              cpu: {{ .Values.user.stable.resources.requests.cpu }}
            limits:
              memory: {{ .Values.user.stable.resources.limits.memory }}
              cpu: {{ .Values.user.stable.resources.limits.cpu }}
          ports:
            - containerPort: {{ .Values.user.port }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-user-config
            - secretRef:
                name: {{ .Chart.Name }}-user-secret
          startupProbe:
            httpGet:
              path: /health
              port: {{ .Values.user.port }}
            initialDelaySeconds: 5
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.user.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.user.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3