apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}-user-hpa-stable
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}-user-deployment-stable
  minReplicas: {{ .Values.user.stable.hpa.minReplicas }}
  maxReplicas: {{ .Values.user.stable.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.user.stable.hpa.resource.cpu.UtilizationPercentage }} 