apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-loan-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}-loan
  ports:
  - port: {{ .Values.loan.port }}
    targetPort: {{ .Values.loan.port }}
  type: {{ .Values.loan.service.type }}